# Generated by Django 5.2 on 2025-05-06 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receta",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("rinde", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recetas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receta",
                "verbose_name_plural": "Recetas",
                "ordering": ["nombre"],
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Unidad",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("abreviacion", models.CharField(max_length=10)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unidades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad",
                "verbose_name_plural": "Unidades",
                "ordering": ["abreviacion"],
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.FloatField()),
                ("precio", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="recetario.unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
                "permissions": [],
            },
        ),
        migrations.CreateModel(
            name="Ingrediente",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cantidad", models.FloatField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredientes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredientes",
                        to="recetario.producto",
                    ),
                ),
                (
                    "receta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="recetario.receta",
                    ),
                ),
                (
                    "unidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ingredientes",
                        to="recetario.unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredientes",
            },
        ),
    ]
