# Generated by Django 5.2 on 2025-11-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0002_producto_stock_minimo_movimientodestock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientodestock',
            options={'ordering': ['-fecha'], 'permissions': [], 'verbose_name': 'Movimiento de Stock', 'verbose_name_plural': 'Movimientos de Stock'},
        ),
    ]
