# Generated by Django 5.2 on 2025-11-10 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetario", "0003_alter_movimientodestock_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="movimientodestock",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Movimiento de Stock",
                "verbose_name_plural": "Movimientos de Stock",
            },
        ),
        migrations.RemoveField(
            model_name="movimientodestock",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="movimientodestock",
            name="producto",
        ),
        migrations.AddField(
            model_name="movimientodestock",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MovimientoDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.FloatField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "movimiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="recetario.movimientodestock",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_de_movimiento",
                        to="recetario.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Preventa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("nombre", models.TextField(blank=True, null=True)),
                ("calle", models.TextField(blank=True, null=True)),
                ("localidad", models.TextField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "movimiento",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="preventa_origen",
                        to="recetario.movimientodestock",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preventas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Preventa",
                "verbose_name_plural": "Preventas",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="PreventaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.FloatField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "preventa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="recetario.preventa",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_preventa",
                        to="recetario.producto",
                    ),
                ),
            ],
        ),
    ]
