# Generated by Django 5.2 on 2025-11-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0004_alter_movimientodestock_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientodestock',
            name='calle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientodestock',
            name='localidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientodestock',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=4),
        ),
    ]
