# Generated by Django 5.2 on 2025-12-18 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetario", "0004_alter_movimientodestock_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientodestock",
            name="calle",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimientodestock",
            name="localidad",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimientodestock",
            name="nombre",
            field=models.TextField(blank=True, null=True),
        ),
    ]
