# Generated by Django 5.2 on 2025-11-27 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetario', '0005_movimientodestock_calle_movimientodestock_localidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='tiempo_produccion_minutos',
            field=models.PositiveIntegerField(default=0, help_text='Tiempo total en minutos para elaborar la receta (preparación + cocción/ensamblaje).'),
        ),
        migrations.CreateModel(
            name='ConfiguracionNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=200)),
                ('tasa_costo_indirecto_por_hora', models.DecimalField(decimal_places=2, help_text='Valor en moneda local por hora operativa (costos indirectos).', max_digits=10)),
                ('porcentaje_margen_beneficio', models.DecimalField(decimal_places=2, default=0, help_text='Margen (%) que se aplicará para sugerir precio de venta.', max_digits=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Negocio',
                'verbose_name_plural': 'Configuraciones de Negocio',
            },
        ),
        migrations.CreateModel(
            name='CostoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_por_hora', models.DecimalField(decimal_places=2, help_text='Costo de mano de obra por hora.', max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costos_laborales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Costo Laboral',
                'verbose_name_plural': 'Costos Laborales',
            },
        ),
    ]
