# Generated by Django 5.2 on 2026-02-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "recetario",
            "0005_movimientodestock_calle_movimientodestock_localidad_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="receta",
            name="costo",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="receta",
            name="costo_unidad",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="receta",
            name="ingredientes_str",
            field=models.TextField(blank=True, default=""),
        ),
    ]
