# Generated by Django 5.2 on 2026-02-21 21:21

from django.db import migrations
from django.utils.timezone import now


JSON_PATH = "recetas_grilla_snapshot.json"


def recalcular_recetas(apps, schema_editor):
    Receta = apps.get_model("recetario", "Receta")
    Ingrediente = apps.get_model("recetario", "Ingrediente")

    data = {
        "generated_at": now().isoformat(),
        "total_recetas": 0,
        "recetas": [],
    }

    for receta in Receta.objects.all():
        ingredientes = (
            Ingrediente.objects
            .filter(receta=receta)
            .select_related("producto")
        )

        total = 0
        nombres = []

        for i in ingredientes:
            if i.producto.cantidad > 0:
                total += (
                    i.producto.precio * i.cantidad / i.producto.cantidad
                )
            nombres.append(i.producto.nombre)

        costo = round(total, 2)
        costo_unidad = round(total / receta.rinde, 2) if receta.rinde else 0
        ingredientes_str = ", ".join(nombres)

        # 🔹 guardar snapshot
        data["recetas"].append({
            "id": receta.id,
            "nombre": receta.nombre,
            "ingredientes": ingredientes_str,
            "costo": costo,
            "costo_unidad": costo_unidad,
            "rinde": receta.rinde,
        })

        # 🔹 persistir en DB
        receta.costo = costo
        receta.costo_unidad = costo_unidad
        receta.ingredientes_str = ingredientes_str
        receta.save(
            update_fields=["costo", "costo_unidad", "ingredientes_str"]
        )

    data["total_recetas"] = len(data["recetas"])


def rollback_recetas(apps, schema_editor):
    """
    Rollback real:
    deja los campos calculados en NULL / vacío
    """
    Receta = apps.get_model("recetario", "Receta")

    Receta.objects.update(
        costo=None,
        costo_unidad=None,
        ingredientes_str=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("recetario", "0006_receta_costo_receta_costo_unidad_and_more"),
    ]

    operations = [
        migrations.RunPython(
            recalcular_recetas,
            rollback_recetas
        )
    ]
