# Generated by Django 5.2 on 2026-02-23 02:03

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetario", "0007_precargar_grilla_recetas"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pg_trgm;"),

        # Producto: mantener índice compuesto (no hay unique equivalente)
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(
                fields=["user", "nombre"],
                name="recetario_p_user_id_3fc389_idx",
            ),
        ),

        # Receta: índice btree global por nombre (déjalo si lo usás para orden/prefijo)
        migrations.AddIndex(
            model_name="receta",
            index=models.Index(
                fields=["nombre"],
                name="idx_receta_nombre",
            ),
        ),
        # Receta: índice GIN trigram para búsquedas icontains
        migrations.AddIndex(
            model_name="receta",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["nombre"],
                name="gin_trgm_receta_nombre",
                opclasses=["gin_trgm_ops"],
            ),
        ),

        migrations.AddConstraint(
            model_name="receta",
            constraint=models.UniqueConstraint(
                fields=("user", "nombre"),
                name="uniq_receta_user_nombre",
            ),
        ),
        migrations.AddConstraint(
            model_name="unidad",
            constraint=models.UniqueConstraint(
                fields=("user", "abreviacion"),
                name="uniq_unidad_user_abrev",
            ),
        ),
        migrations.AddConstraint(
            model_name="unidad",
            constraint=models.UniqueConstraint(
                fields=("user", "nombre"),
                name="uniq_unidad_user_nombre",
            ),
        ),
    ]
