# Generated by Django 5.2 on 2026-03-12 23:58

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recetario", "0008_ingrediente_idx_ing_receta_producto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="producto",
            index=models.Index(fields=["nombre"], name="idx_producto_nombre"),
        ),
        migrations.AddIndex(
            model_name="producto",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["nombre"],
                name="gin_trgm_producto_nombre",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="receta",
            index=models.Index(
                fields=["user", "nombre"], name="idx_receta_user_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="unidad",
            index=models.Index(
                fields=["user", "abreviacion"], name="idx_unidad_user_abrev"
            ),
        ),
        migrations.AddIndex(
            model_name="unidad",
            index=models.Index(
                fields=["user", "nombre"], name="idx_unidad_user_nombre"
            ),
        ),
    ]
