[tool.black]
line-length = 88
target-version = ["py310"]
include = "\\.pyi?$"
exclude = '''
/(
    \.git
  | \.venv
  | env
  | build
  | dist
)/ 
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
known_first_party = [
    "recetario",
    "users"
]

[tool.mypy]
python_version = "3.10"
ignore_missing_imports = true
strict = true
show_error_codes = true
pretty = true
namespace_packages = true
explicit_package_bases = true
plugins = [
    "mypy_django_plugin.main",
    "mypy_drf_plugin.main"
]

[mypy.plugins.django-stubs]
django_settings_module = "hub.settings"

[tool.pylint]
load-plugins = ["pylint_django"]

[tool.pylint.'MESSAGES CONTROL']
disable = [
    "C0114", # missing-module-docstring
    "C0115", # missing-class-docstring
    "C0116", # missing-function-docstring
    "R0903", # too-few-public-methods
    "R0801", # duplicate-code
    "E1101"  # no-member (para modelos de Django)
]

[tool.pylint.format]
max-line-length = 88

[tool.pylint.'MASTER']
ignore = [
    "build",
    "dist",
    ".venv",
    "env"
]

[tool.django-stubs]
django_settings_module = "hub.settings"
strict_settings = true
