name: Django CI & Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch: # Permite ejecutar el workflow manualmente desde GitHub

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: localhost
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      PYTHONPATH: ${{ github.workspace }}
      DJANGO_SETTINGS_MODULE: hub.settings
      RUNNING_TESTS: "1"

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run migrations
        run: |
          python manage.py migrate --noinput
          python manage.py collectstatic --noinput

      - name: Run linters
        run: |
          black --check .
          flake8 .
          isort --check-only .
          pylint hub/ recetario/ tests/ users/
          mypy --install-types --non-interactive .

      - name: Run tests
        run: |
          pytest --cov=hub --cov=recetario --cov=tests --cov=users --cov-report=term-missing --cov-fail-under=80
          coverage xml

  docker:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hub-backend:latest

      - name: Inspect Docker image size
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/hub-backend:latest
          docker image inspect ${{ secrets.DOCKER_USERNAME }}/hub-backend:latest --format='{{.Size}} bytes'
