name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_NAME: testdb
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: localhost
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-django coverage black flake8 isort pylint mypy

      - name: Run linters
        run: |
          isort --check-only .
          black --check .
          flake8 .
          pylint --load-plugins pylint_django --django-settings-module=your_project.settings $(git ls-files '*.py')
          mypy --install-types --non-interactive --config-file=mypy.ini .

      - name: Run tests
        run: |
          coverage run -m pytest
          coverage report
          coverage xml